// GLSL shader autogenerated by cg2glsl.py.
#if defined(VERTEX)

#if __VERSION__ >= 130
#define COMPAT_VARYING out
#define COMPAT_ATTRIBUTE in
#define COMPAT_TEXTURE texture
#else
#define COMPAT_VARYING varying
#define COMPAT_ATTRIBUTE attribute
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec4 _t7;
COMPAT_VARYING     vec4 _t6;
COMPAT_VARYING     vec4 _t5;
COMPAT_VARYING     vec4 _t4;
COMPAT_VARYING     vec4 _t3;
COMPAT_VARYING     vec4 _t2;
COMPAT_VARYING     vec4 _t1;
COMPAT_VARYING     vec2 _texCoord2;
COMPAT_VARYING     vec4 _color1;
COMPAT_VARYING     vec4 _position1;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct out_vertex {
    vec4 _position1;
    vec4 _color1;
    vec2 _texCoord2;
    vec4 _t1;
    vec4 _t2;
    vec4 _t3;
    vec4 _t4;
    vec4 _t5;
    vec4 _t6;
    vec4 _t7;
};
out_vertex _ret_0;
input_dummy _IN1;
vec4 _r0006;
COMPAT_ATTRIBUTE vec4 VertexCoord;
COMPAT_ATTRIBUTE vec4 COLOR;
COMPAT_ATTRIBUTE vec4 TexCoord;
COMPAT_VARYING vec4 COL0;
COMPAT_VARYING vec4 TEX0;
COMPAT_VARYING vec4 TEX1;
COMPAT_VARYING vec4 TEX2;
COMPAT_VARYING vec4 TEX3;
COMPAT_VARYING vec4 TEX4;
COMPAT_VARYING vec4 TEX5;
COMPAT_VARYING vec4 TEX6;
COMPAT_VARYING vec4 TEX7;
 
uniform mat4 MVPMatrix;
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    out_vertex _OUT;
    vec2 _ps;
    vec2 _texCoord;
    _r0006 = VertexCoord.x*MVPMatrix[0];
    _r0006 = _r0006 + VertexCoord.y*MVPMatrix[1];
    _r0006 = _r0006 + VertexCoord.z*MVPMatrix[2];
    _r0006 = _r0006 + VertexCoord.w*MVPMatrix[3];
    _ps = vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y);
    _texCoord = TexCoord.xy + vec2( 1.00000001E-07, 1.00000001E-07);
    _OUT._t1 = _texCoord.xxxy + vec4(-_ps.x, 0.00000000E+00, _ps.x, -2.00000000E+00*_ps.y);
    _OUT._t2 = _texCoord.xxxy + vec4(-_ps.x, 0.00000000E+00, _ps.x, -_ps.y);
    _OUT._t3 = _texCoord.xxxy + vec4(-_ps.x, 0.00000000E+00, _ps.x, 0.00000000E+00);
    _OUT._t4 = _texCoord.xxxy + vec4(-_ps.x, 0.00000000E+00, _ps.x, _ps.y);
    _OUT._t5 = _texCoord.xxxy + vec4(-_ps.x, 0.00000000E+00, _ps.x, 2.00000000E+00*_ps.y);
    _OUT._t6 = _texCoord.xyyy + vec4(-2.00000000E+00*_ps.x, -_ps.y, 0.00000000E+00, _ps.y);
    _OUT._t7 = _texCoord.xyyy + vec4(2.00000000E+00*_ps.x, -_ps.y, 0.00000000E+00, _ps.y);
    _ret_0._position1 = _r0006;
    _ret_0._color1 = COLOR;
    _ret_0._texCoord2 = _texCoord;
    _ret_0._t1 = _OUT._t1;
    _ret_0._t2 = _OUT._t2;
    _ret_0._t3 = _OUT._t3;
    _ret_0._t4 = _OUT._t4;
    _ret_0._t5 = _OUT._t5;
    _ret_0._t6 = _OUT._t6;
    _ret_0._t7 = _OUT._t7;
    gl_Position = _r0006;
    COL0 = COLOR;
    TEX0.xy = _texCoord;
    TEX1 = _OUT._t1;
    TEX2 = _OUT._t2;
    TEX3 = _OUT._t3;
    TEX4 = _OUT._t4;
    TEX5 = _OUT._t5;
    TEX6 = _OUT._t6;
    TEX7 = _OUT._t7;
    return;
    COL0 = _ret_0._color1;
    TEX0.xy = _ret_0._texCoord2;
    TEX1 = _ret_0._t1;
    TEX2 = _ret_0._t2;
    TEX3 = _ret_0._t3;
    TEX4 = _ret_0._t4;
    TEX5 = _ret_0._t5;
    TEX6 = _ret_0._t6;
    TEX7 = _ret_0._t7;
} 
#elif defined(FRAGMENT)

#if __VERSION__ >= 130
#define COMPAT_VARYING in
#define COMPAT_TEXTURE texture
out vec4 FragColor;
#else
#define COMPAT_VARYING varying
#define FragColor gl_FragColor
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec4 _t7;
COMPAT_VARYING     vec4 _t6;
COMPAT_VARYING     vec4 _t5;
COMPAT_VARYING     vec4 _t4;
COMPAT_VARYING     vec4 _t3;
COMPAT_VARYING     vec4 _t21;
COMPAT_VARYING     vec4 _t11;
COMPAT_VARYING     vec2 _texCoord;
COMPAT_VARYING     vec4 _color;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct out_vertex {
    vec4 _color;
    vec2 _texCoord;
    vec4 _t11;
    vec4 _t21;
    vec4 _t3;
    vec4 _t4;
    vec4 _t5;
    vec4 _t6;
    vec4 _t7;
};
vec4 _ret_0;
vec3 _TMP21;
vec3 _TMP15;
vec3 _TMP14;
vec3 _TMP13;
vec3 _TMP12;
vec3 _TMP11;
vec3 _TMP10;
vec3 _TMP20;
vec3 _TMP19;
vec3 _TMP18;
vec3 _TMP17;
vec4 _TMP9;
vec4 _TMP8;
vec4 _TMP7;
vec4 _TMP6;
vec4 _TMP5;
vec4 _TMP4;
vec4 _TMP3;
vec4 _TMP2;
vec4 _TMP1;
vec2 _TMP0;
uniform sampler2D Texture;
input_dummy _IN1;
vec2 _x0030;
vec3 _TMP260050[4];
vec3 _m0050;
vec3 _t0050;
vec3 _TMP59;
vec3 _a0060;
vec3 _TMP260066[4];
vec3 _m0066;
vec3 _t0066;
vec3 _TMP75;
vec3 _a0076;
vec3 _TMP97;
COMPAT_VARYING vec4 TEX0;
COMPAT_VARYING vec4 TEX1;
COMPAT_VARYING vec4 TEX2;
COMPAT_VARYING vec4 TEX3;
COMPAT_VARYING vec4 TEX4;
COMPAT_VARYING vec4 TEX5;
COMPAT_VARYING vec4 TEX6;
COMPAT_VARYING vec4 TEX7;
 
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    vec2 _fp;
    vec3 _res;
    vec3 _a;
    vec3 _b;
    _x0030 = TEX0.xy*TextureSize;
    _TMP0 = fract(_x0030);
    _fp = 2.00000000E+00*_TMP0 - 1.00000000E+00;
    _TMP1 = COMPAT_TEXTURE(Texture, TEX1.yw);
    _TMP2 = COMPAT_TEXTURE(Texture, TEX2.yw);
    _TMP3 = COMPAT_TEXTURE(Texture, TEX3.xw);
    _TMP4 = COMPAT_TEXTURE(Texture, TEX3.yw);
    _TMP5 = COMPAT_TEXTURE(Texture, TEX3.zw);
    _TMP6 = COMPAT_TEXTURE(Texture, TEX4.yw);
    _TMP7 = COMPAT_TEXTURE(Texture, TEX5.yw);
    _TMP8 = COMPAT_TEXTURE(Texture, TEX6.xz);
    _TMP9 = COMPAT_TEXTURE(Texture, TEX7.xz);
    _TMP260050[0] = _TMP2.xyz - _TMP1.xyz;
    _TMP260050[1] = _TMP4.xyz - _TMP2.xyz;
    _TMP260050[2] = _TMP6.xyz - _TMP4.xyz;
    _TMP260050[3] = _TMP7.xyz - _TMP6.xyz;
    _m0050 = vec3(_TMP4.x < 5.00000000E-01 ? _TMP4.x : (1.00000000E+00 - _TMP4.xyz).x, _TMP4.y < 5.00000000E-01 ? _TMP4.y : (1.00000000E+00 - _TMP4.xyz).y, _TMP4.z < 5.00000000E-01 ? _TMP4.z : (1.00000000E+00 - _TMP4.xyz).z);
    _TMP17 = abs(_TMP260050[1]);
    _TMP18 = abs(_TMP260050[2]);
    _TMP19 = min(_TMP17, _TMP18);
    _TMP20 = min(_m0050, _TMP19);
    _m0050 = 2.00000000E+00*_TMP20;
    _t0050 = (7.00000000E+00*(_TMP260050[1] + _TMP260050[2]) - 3.00000000E+00*(_TMP260050[0] + _TMP260050[3]))/1.60000000E+01;
    _a0060 = -_m0050;
    _TMP21 = min(_m0050, _t0050);
    _TMP59 = max(_a0060, _TMP21);
    _TMP260066[0] = _TMP3.xyz - _TMP8.xyz;
    _TMP260066[1] = _TMP4.xyz - _TMP3.xyz;
    _TMP260066[2] = _TMP5.xyz - _TMP4.xyz;
    _TMP260066[3] = _TMP9.xyz - _TMP5.xyz;
    _m0066 = vec3(_TMP4.x < 5.00000000E-01 ? _TMP4.x : (1.00000000E+00 - _TMP4.xyz).x, _TMP4.y < 5.00000000E-01 ? _TMP4.y : (1.00000000E+00 - _TMP4.xyz).y, _TMP4.z < 5.00000000E-01 ? _TMP4.z : (1.00000000E+00 - _TMP4.xyz).z);
    _TMP17 = abs(_TMP260066[1]);
    _TMP18 = abs(_TMP260066[2]);
    _TMP19 = min(_TMP17, _TMP18);
    _TMP20 = min(_m0066, _TMP19);
    _m0066 = 2.00000000E+00*_TMP20;
    _t0066 = (7.00000000E+00*(_TMP260066[1] + _TMP260066[2]) - 3.00000000E+00*(_TMP260066[0] + _TMP260066[3]))/1.60000000E+01;
    _a0076 = -_m0066;
    _TMP21 = min(_m0066, _t0066);
    _TMP75 = max(_a0076, _TMP21);
    _res = _TMP4.xyz + _fp.y*_TMP59 + _fp.x*_TMP75;
    _TMP10 = min(_TMP2.xyz, _TMP3.xyz);
    _TMP11 = min(_TMP10, _TMP4.xyz);
    _TMP12 = min(_TMP11, _TMP5.xyz);
    _a = min(_TMP12, _TMP6.xyz);
    _TMP13 = max(_TMP2.xyz, _TMP3.xyz);
    _TMP14 = max(_TMP13, _TMP4.xyz);
    _TMP15 = max(_TMP14, _TMP5.xyz);
    _b = max(_TMP15, _TMP6.xyz);
    _TMP21 = min(_b, _res);
    _TMP97 = max(_a, _TMP21);
    _ret_0 = vec4(_TMP97.x, _TMP97.y, _TMP97.z, 1.00000000E+00);
    FragColor = _ret_0;
    return;
} 
#endif
