// GLSL shader autogenerated by cg2glsl.py.
#if defined(VERTEX)

#if __VERSION__ >= 130
#define COMPAT_VARYING out
#define COMPAT_ATTRIBUTE in
#define COMPAT_TEXTURE texture
#else
#define COMPAT_VARYING varying
#define COMPAT_ATTRIBUTE attribute
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec2 _texCoord;
COMPAT_VARYING     vec4 _color1;
COMPAT_VARYING     vec4 _position1;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct out_vertex {
    vec4 _position1;
    vec4 _color1;
    vec2 _texCoord;
};
out_vertex _ret_0;
vec4 _r0008;
COMPAT_ATTRIBUTE vec4 VertexCoord;
COMPAT_ATTRIBUTE vec4 COLOR;
COMPAT_ATTRIBUTE vec4 TexCoord;
COMPAT_VARYING vec4 COL0;
COMPAT_VARYING vec4 TEX0;
 
uniform mat4 MVPMatrix;
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    _r0008 = VertexCoord.x*MVPMatrix[0];
    _r0008 = _r0008 + VertexCoord.y*MVPMatrix[1];
    _r0008 = _r0008 + VertexCoord.z*MVPMatrix[2];
    _r0008 = _r0008 + VertexCoord.w*MVPMatrix[3];
    _ret_0._position1 = _r0008;
    _ret_0._color1 = COLOR;
    _ret_0._texCoord = TexCoord.xy;
    gl_Position = _r0008;
    COL0 = COLOR;
    TEX0.xy = TexCoord.xy;
    return;
    COL0 = _ret_0._color1;
    TEX0.xy = _ret_0._texCoord;
} 
#elif defined(FRAGMENT)

#if __VERSION__ >= 130
#define COMPAT_VARYING in
#define COMPAT_TEXTURE texture
out vec4 FragColor;
#else
#define COMPAT_VARYING varying
#define FragColor gl_FragColor
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec2 _texCoord;
COMPAT_VARYING     vec4 _color;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct out_vertex {
    vec4 _color;
    vec2 _texCoord;
};
vec4 _ret_0;
vec4 _TMP52;
vec4 _TMP51;
vec4 _TMP50;
vec4 _TMP49;
float _TMP57;
float _TMP56;
float _TMP55;
float _TMP54;
float _TMP43;
float _TMP41;
float _TMP39;
float _TMP37;
float _TMP35;
float _TMP33;
float _TMP31;
float _TMP29;
float _TMP27;
float _TMP25;
float _TMP23;
float _TMP21;
float _TMP19;
float _TMP17;
float _TMP15;
float _TMP13;
vec4 _TMP42;
vec4 _TMP40;
vec4 _TMP38;
vec4 _TMP36;
vec4 _TMP34;
vec4 _TMP32;
vec4 _TMP30;
vec4 _TMP28;
vec4 _TMP26;
vec4 _TMP24;
vec4 _TMP22;
vec4 _TMP20;
vec4 _TMP18;
vec4 _TMP16;
vec4 _TMP14;
vec4 _TMP12;
float _TMP11;
float _TMP9;
float _TMP7;
float _TMP5;
vec4 _TMP10;
vec4 _TMP8;
vec4 _TMP6;
vec4 _TMP4;
float _TMP3;
float _TMP2;
float _TMP1;
float _TMP0;
uniform sampler2D Texture;
input_dummy _IN1;
float _x0102;
float _x0104;
float _x0106;
float _x0108;
vec2 _c0110;
vec2 _c0114;
vec2 _c0118;
vec2 _c0122;
vec2 _c0126;
vec2 _c0130;
vec2 _c0134;
vec2 _c0138;
vec2 _c0142;
vec2 _c0146;
vec2 _c0150;
vec2 _c0154;
vec2 _c0158;
vec2 _c0162;
vec2 _c0166;
vec2 _c0170;
vec2 _c0174;
vec2 _c0178;
vec2 _c0182;
vec2 _c0186;
vec2 _C0192[2];
vec2 _C0194[2];
vec2 _r0196;
float _TMP205;
float _x0206;
vec2 _c0212;
vec2 _c0214;
vec2 _c0216;
vec2 _c0218;
vec3 _C0220[1];
COMPAT_VARYING vec4 TEX0;
 
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    vec4 _c0;
    vec2 _R[2];
    vec2 _r;
    vec4 _y1;
    vec2 _a;
    vec3 _TMP63[2];
    vec2 _TMP67[2];
    vec2 _TMP68[4];
    vec2 _TMP69[2];
    vec2 _TMP70[4];
    vec2 _TMP71[4];
    vec2 _TMP72[4];
    _c0 = COMPAT_TEXTURE(Texture, TEX0.xy);
    _x0102 = (TEX0.x*TextureSize.x)/2.00000000E+00;
    _TMP0 = fract(_x0102);
    _x0104 = TEX0.y*TextureSize.y;
    _TMP1 = fract(_x0104);
    _x0106 = (TEX0.x*TextureSize.x)/2.00000000E+00;
    _TMP2 = fract(_x0106);
    _x0108 = TEX0.y*TextureSize.y;
    _TMP3 = fract(_x0108);
    if (_TMP0 < 5.00000000E-01 && _TMP1 < 5.00000000E-01 || _TMP2 > 5.00000000E-01 && _TMP3 > 5.00000000E-01) { 
        FragColor = _c0;
        return;
    } 
    _c0110 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -1.00000000E+00, 0.00000000E+00);
    _TMP4 = COMPAT_TEXTURE(Texture, _c0110);
    _TMP5 = dot(_TMP4.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0114 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 1.00000000E+00, 0.00000000E+00);
    _TMP6 = COMPAT_TEXTURE(Texture, _c0114);
    _TMP7 = dot(_TMP6.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0118 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 0.00000000E+00, 1.00000000E+00);
    _TMP8 = COMPAT_TEXTURE(Texture, _c0118);
    _TMP9 = dot(_TMP8.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0122 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 0.00000000E+00, -1.00000000E+00);
    _TMP10 = COMPAT_TEXTURE(Texture, _c0122);
    _TMP11 = dot(_TMP10.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _y1 = vec4(_TMP5, _TMP7, _TMP9, _TMP11);
    _c0126 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -3.00000000E+00, 0.00000000E+00);
    _TMP12 = COMPAT_TEXTURE(Texture, _c0126);
    _TMP13 = dot(_TMP12.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0130 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 1.00000000E+00, 0.00000000E+00);
    _TMP14 = COMPAT_TEXTURE(Texture, _c0130);
    _TMP15 = dot(_TMP14.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0134 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -1.00000000E+00, 2.00000000E+00);
    _TMP16 = COMPAT_TEXTURE(Texture, _c0134);
    _TMP17 = dot(_TMP16.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0138 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -1.00000000E+00, -2.00000000E+00);
    _TMP18 = COMPAT_TEXTURE(Texture, _c0138);
    _TMP19 = dot(_TMP18.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0142 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -1.00000000E+00, 0.00000000E+00);
    _TMP20 = COMPAT_TEXTURE(Texture, _c0142);
    _TMP21 = dot(_TMP20.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0146 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 3.00000000E+00, 0.00000000E+00);
    _TMP22 = COMPAT_TEXTURE(Texture, _c0146);
    _TMP23 = dot(_TMP22.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0150 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 1.00000000E+00, 2.00000000E+00);
    _TMP24 = COMPAT_TEXTURE(Texture, _c0150);
    _TMP25 = dot(_TMP24.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0154 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 1.00000000E+00, -2.00000000E+00);
    _TMP26 = COMPAT_TEXTURE(Texture, _c0154);
    _TMP27 = dot(_TMP26.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0158 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -2.00000000E+00, 1.00000000E+00);
    _TMP28 = COMPAT_TEXTURE(Texture, _c0158);
    _TMP29 = dot(_TMP28.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0162 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 2.00000000E+00, 1.00000000E+00);
    _TMP30 = COMPAT_TEXTURE(Texture, _c0162);
    _TMP31 = dot(_TMP30.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0166 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 0.00000000E+00, 3.00000000E+00);
    _TMP32 = COMPAT_TEXTURE(Texture, _c0166);
    _TMP33 = dot(_TMP32.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0170 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 0.00000000E+00, -1.00000000E+00);
    _TMP34 = COMPAT_TEXTURE(Texture, _c0170);
    _TMP35 = dot(_TMP34.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0174 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -2.00000000E+00, -1.00000000E+00);
    _TMP36 = COMPAT_TEXTURE(Texture, _c0174);
    _TMP37 = dot(_TMP36.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0178 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 2.00000000E+00, -1.00000000E+00);
    _TMP38 = COMPAT_TEXTURE(Texture, _c0178);
    _TMP39 = dot(_TMP38.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0182 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 0.00000000E+00, 1.00000000E+00);
    _TMP40 = COMPAT_TEXTURE(Texture, _c0182);
    _TMP41 = dot(_TMP40.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0186 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 0.00000000E+00, -3.00000000E+00);
    _TMP42 = COMPAT_TEXTURE(Texture, _c0186);
    _TMP43 = dot(_TMP42.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _TMP72[0] = vec2(_TMP13 + _TMP15, _TMP17 + _TMP19);
    _TMP72[1] = vec2(_TMP21 + _TMP23, _TMP25 + _TMP27);
    _TMP72[2] = vec2(_TMP29 + _TMP31, _TMP33 + _TMP35);
    _TMP72[3] = vec2(_TMP37 + _TMP39, _TMP41 + _TMP43);
    _TMP71[0] = 4.00000000E+00*_TMP72[0];
    _TMP71[1] = 4.00000000E+00*_TMP72[1];
    _TMP71[2] = 4.00000000E+00*_TMP72[2];
    _TMP71[3] = 4.00000000E+00*_TMP72[3];
    _C0192[0] = _TMP72[0].x*_TMP71[0] + _TMP72[1].x*_TMP71[1] + _TMP72[2].x*_TMP71[2] + _TMP72[3].x*_TMP71[3];
    _TMP70[0] = 4.00000000E+00*_TMP72[0];
    _TMP70[1] = 4.00000000E+00*_TMP72[1];
    _TMP70[2] = 4.00000000E+00*_TMP72[2];
    _TMP70[3] = 4.00000000E+00*_TMP72[3];
    _C0194[1] = _TMP72[0].y*_TMP70[0] + _TMP72[1].y*_TMP70[1] + _TMP72[2].y*_TMP70[2] + _TMP72[3].y*_TMP70[3];
    _TMP69[0] = _C0192[0];
    _R[1] = _C0194[1];
    _TMP68[0] = 4.00000000E+00*_TMP72[0];
    _TMP68[1] = 4.00000000E+00*_TMP72[1];
    _TMP68[2] = 4.00000000E+00*_TMP72[2];
    _TMP68[3] = 4.00000000E+00*_TMP72[3];
    _r0196 = _y1.x*_TMP68[0];
    _r0196 = _r0196 + _y1.y*_TMP68[1];
    _r0196 = _r0196 + _y1.z*_TMP68[2];
    _r0196 = _r0196 + _y1.w*_TMP68[3];
    _r = _r0196;
    _c0110 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -2.00000000E+00, -1.00000000E+00);
    _TMP4 = COMPAT_TEXTURE(Texture, _c0110);
    _TMP5 = dot(_TMP4.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0114 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 2.00000000E+00, 1.00000000E+00);
    _TMP6 = COMPAT_TEXTURE(Texture, _c0114);
    _TMP7 = dot(_TMP6.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0118 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -1.00000000E+00, 2.00000000E+00);
    _TMP8 = COMPAT_TEXTURE(Texture, _c0118);
    _TMP9 = dot(_TMP8.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0122 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 1.00000000E+00, -2.00000000E+00);
    _TMP10 = COMPAT_TEXTURE(Texture, _c0122);
    _TMP11 = dot(_TMP10.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _y1 = vec4(_TMP5, _TMP7, _TMP9, _TMP11);
    _c0126 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -4.00000000E+00, -1.00000000E+00);
    _TMP12 = COMPAT_TEXTURE(Texture, _c0126);
    _TMP13 = dot(_TMP12.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0130 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 0.00000000E+00, -1.00000000E+00);
    _TMP14 = COMPAT_TEXTURE(Texture, _c0130);
    _TMP15 = dot(_TMP14.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0134 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -2.00000000E+00, 1.00000000E+00);
    _TMP16 = COMPAT_TEXTURE(Texture, _c0134);
    _TMP17 = dot(_TMP16.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0138 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -2.00000000E+00, -3.00000000E+00);
    _TMP18 = COMPAT_TEXTURE(Texture, _c0138);
    _TMP19 = dot(_TMP18.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0142 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 0.00000000E+00, 1.00000000E+00);
    _TMP20 = COMPAT_TEXTURE(Texture, _c0142);
    _TMP21 = dot(_TMP20.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0146 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 4.00000000E+00, 1.00000000E+00);
    _TMP22 = COMPAT_TEXTURE(Texture, _c0146);
    _TMP23 = dot(_TMP22.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0150 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 2.00000000E+00, 3.00000000E+00);
    _TMP24 = COMPAT_TEXTURE(Texture, _c0150);
    _TMP25 = dot(_TMP24.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0154 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 2.00000000E+00, -1.00000000E+00);
    _TMP26 = COMPAT_TEXTURE(Texture, _c0154);
    _TMP27 = dot(_TMP26.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0158 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -3.00000000E+00, 2.00000000E+00);
    _TMP28 = COMPAT_TEXTURE(Texture, _c0158);
    _TMP29 = dot(_TMP28.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0162 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 1.00000000E+00, 2.00000000E+00);
    _TMP30 = COMPAT_TEXTURE(Texture, _c0162);
    _TMP31 = dot(_TMP30.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0166 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -1.00000000E+00, 4.00000000E+00);
    _TMP32 = COMPAT_TEXTURE(Texture, _c0166);
    _TMP33 = dot(_TMP32.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0170 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -1.00000000E+00, 0.00000000E+00);
    _TMP34 = COMPAT_TEXTURE(Texture, _c0170);
    _TMP35 = dot(_TMP34.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0174 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -1.00000000E+00, -2.00000000E+00);
    _TMP36 = COMPAT_TEXTURE(Texture, _c0174);
    _TMP37 = dot(_TMP36.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0178 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 3.00000000E+00, -2.00000000E+00);
    _TMP38 = COMPAT_TEXTURE(Texture, _c0178);
    _TMP39 = dot(_TMP38.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0182 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 1.00000000E+00, 0.00000000E+00);
    _TMP40 = COMPAT_TEXTURE(Texture, _c0182);
    _TMP41 = dot(_TMP40.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0186 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 1.00000000E+00, -4.00000000E+00);
    _TMP42 = COMPAT_TEXTURE(Texture, _c0186);
    _TMP43 = dot(_TMP42.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _TMP72[0] = vec2(_TMP13 + _TMP15, _TMP17 + _TMP19);
    _TMP72[1] = vec2(_TMP21 + _TMP23, _TMP25 + _TMP27);
    _TMP72[2] = vec2(_TMP29 + _TMP31, _TMP33 + _TMP35);
    _TMP72[3] = vec2(_TMP37 + _TMP39, _TMP41 + _TMP43);
    _C0192[0] = _TMP72[0].x*_TMP72[0] + _TMP72[1].x*_TMP72[1] + _TMP72[2].x*_TMP72[2] + _TMP72[3].x*_TMP72[3];
    _C0194[1] = _TMP72[0].y*_TMP72[0] + _TMP72[1].y*_TMP72[1] + _TMP72[2].y*_TMP72[2] + _TMP72[3].y*_TMP72[3];
    _TMP69[0] = _TMP69[0] + _C0192[0];
    _TMP69[1] = _R[1] + _C0194[1];
    _r0196 = _y1.x*_TMP72[0];
    _r0196 = _r0196 + _y1.y*_TMP72[1];
    _r0196 = _r0196 + _y1.z*_TMP72[2];
    _r0196 = _r0196 + _y1.w*_TMP72[3];
    _r = _r + _r0196;
    _c0110 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -3.00000000E+00, -2.00000000E+00);
    _TMP4 = COMPAT_TEXTURE(Texture, _c0110);
    _TMP5 = dot(_TMP4.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0114 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 3.00000000E+00, 2.00000000E+00);
    _TMP6 = COMPAT_TEXTURE(Texture, _c0114);
    _TMP7 = dot(_TMP6.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0118 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -2.00000000E+00, 3.00000000E+00);
    _TMP8 = COMPAT_TEXTURE(Texture, _c0118);
    _TMP9 = dot(_TMP8.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0122 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 2.00000000E+00, -3.00000000E+00);
    _TMP10 = COMPAT_TEXTURE(Texture, _c0122);
    _TMP11 = dot(_TMP10.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _y1 = vec4(_TMP5, _TMP7, _TMP9, _TMP11);
    _c0126 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -5.00000000E+00, -2.00000000E+00);
    _TMP12 = COMPAT_TEXTURE(Texture, _c0126);
    _TMP13 = dot(_TMP12.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0130 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -1.00000000E+00, -2.00000000E+00);
    _TMP14 = COMPAT_TEXTURE(Texture, _c0130);
    _TMP15 = dot(_TMP14.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0134 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -3.00000000E+00, 0.00000000E+00);
    _TMP16 = COMPAT_TEXTURE(Texture, _c0134);
    _TMP17 = dot(_TMP16.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0138 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -3.00000000E+00, -4.00000000E+00);
    _TMP18 = COMPAT_TEXTURE(Texture, _c0138);
    _TMP19 = dot(_TMP18.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0142 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 1.00000000E+00, 2.00000000E+00);
    _TMP20 = COMPAT_TEXTURE(Texture, _c0142);
    _TMP21 = dot(_TMP20.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0146 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 5.00000000E+00, 2.00000000E+00);
    _TMP22 = COMPAT_TEXTURE(Texture, _c0146);
    _TMP23 = dot(_TMP22.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0150 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 3.00000000E+00, 4.00000000E+00);
    _TMP24 = COMPAT_TEXTURE(Texture, _c0150);
    _TMP25 = dot(_TMP24.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0154 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 3.00000000E+00, 0.00000000E+00);
    _TMP26 = COMPAT_TEXTURE(Texture, _c0154);
    _TMP27 = dot(_TMP26.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0158 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -4.00000000E+00, 3.00000000E+00);
    _TMP28 = COMPAT_TEXTURE(Texture, _c0158);
    _TMP29 = dot(_TMP28.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0162 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 0.00000000E+00, 3.00000000E+00);
    _TMP30 = COMPAT_TEXTURE(Texture, _c0162);
    _TMP31 = dot(_TMP30.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0166 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -2.00000000E+00, 5.00000000E+00);
    _TMP32 = COMPAT_TEXTURE(Texture, _c0166);
    _TMP33 = dot(_TMP32.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0170 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -2.00000000E+00, 1.00000000E+00);
    _TMP34 = COMPAT_TEXTURE(Texture, _c0170);
    _TMP35 = dot(_TMP34.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0174 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 0.00000000E+00, -3.00000000E+00);
    _TMP36 = COMPAT_TEXTURE(Texture, _c0174);
    _TMP37 = dot(_TMP36.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0178 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 4.00000000E+00, -3.00000000E+00);
    _TMP38 = COMPAT_TEXTURE(Texture, _c0178);
    _TMP39 = dot(_TMP38.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0182 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 2.00000000E+00, -1.00000000E+00);
    _TMP40 = COMPAT_TEXTURE(Texture, _c0182);
    _TMP41 = dot(_TMP40.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _c0186 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 2.00000000E+00, -5.00000000E+00);
    _TMP42 = COMPAT_TEXTURE(Texture, _c0186);
    _TMP43 = dot(_TMP42.xyz, vec3( 2.12599993E-01, 7.15200007E-01, 7.22000003E-02));
    _TMP72[0] = vec2(_TMP13 + _TMP15, _TMP17 + _TMP19);
    _TMP72[1] = vec2(_TMP21 + _TMP23, _TMP25 + _TMP27);
    _TMP72[2] = vec2(_TMP29 + _TMP31, _TMP33 + _TMP35);
    _TMP72[3] = vec2(_TMP37 + _TMP39, _TMP41 + _TMP43);
    _C0192[0] = _TMP72[0].x*_TMP72[0] + _TMP72[1].x*_TMP72[1] + _TMP72[2].x*_TMP72[2] + _TMP72[3].x*_TMP72[3];
    _C0194[1] = _TMP72[0].y*_TMP72[0] + _TMP72[1].y*_TMP72[1] + _TMP72[2].y*_TMP72[2] + _TMP72[3].y*_TMP72[3];
    _TMP69[0] = _TMP69[0] + _C0192[0];
    _TMP69[1] = _TMP69[1] + _C0194[1];
    _r0196 = _y1.x*_TMP72[0];
    _r0196 = _r0196 + _y1.y*_TMP72[1];
    _r0196 = _r0196 + _y1.z*_TMP72[2];
    _r0196 = _r0196 + _y1.w*_TMP72[3];
    _r = _r + _r0196;
    _TMP67[0] = _TMP69[0]/2.40000000E+01;
    _TMP67[1] = _TMP69[1]/2.40000000E+01;
    _r = _r/2.40000000E+01;
    _TMP54 = _r.x*_TMP67[1].y - _r.y*_TMP67[1].x;
    _TMP55 = _TMP67[0].x*_r.y - _TMP67[0].y*_r.x;
    _TMP56 = _TMP67[0].x*_TMP67[1].y - _TMP67[0].y*_TMP67[1].x;
    _a = vec2(_TMP54, _TMP55)/_TMP56;
    _x0206 = _a.x - _a.y;
    _TMP57 = min(1.00000000E+00, _x0206);
    _TMP205 = max(-1.00000000E+00, _TMP57);
    _a = 2.50000000E-01 + vec2( 5.00000000E-01, -5.00000000E-01)*_TMP205;
    _c0212 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( -1.00000000E+00, 0.00000000E+00);
    _TMP49 = COMPAT_TEXTURE(Texture, _c0212);
    _c0214 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 1.00000000E+00, 0.00000000E+00);
    _TMP50 = COMPAT_TEXTURE(Texture, _c0214);
    _c0216 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 0.00000000E+00, 1.00000000E+00);
    _TMP51 = COMPAT_TEXTURE(Texture, _c0216);
    _c0218 = TEX0.xy + vec2(1.00000000E+00/TextureSize.x, 5.00000000E-01/TextureSize.y)*vec2( 0.00000000E+00, -1.00000000E+00);
    _TMP52 = COMPAT_TEXTURE(Texture, _c0218);
    _TMP63[0] = _TMP49.xyz + _TMP50.xyz;
    _TMP63[1] = _TMP51.xyz + _TMP52.xyz;
    _C0220[0] = _a.x*_TMP63[0] + _a.y*_TMP63[1];
    _ret_0 = vec4(_C0220[0].x, _C0220[0].y, _C0220[0].z, 1.00000000E+00);
    FragColor = _ret_0;
    return;
} 
#endif
