// GLSL shader autogenerated by cg2glsl.py.
#if defined(VERTEX)

#if __VERSION__ >= 130
#define COMPAT_VARYING out
#define COMPAT_ATTRIBUTE in
#define COMPAT_TEXTURE texture
#else
#define COMPAT_VARYING varying
#define COMPAT_ATTRIBUTE attribute
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec2 _texCoord;
COMPAT_VARYING     vec4 _color1;
COMPAT_VARYING     vec4 _position1;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct out_vertex {
    vec4 _position1;
    vec4 _color1;
    vec2 _texCoord;
};
out_vertex _ret_0;
vec4 _r0008;
COMPAT_ATTRIBUTE vec4 VertexCoord;
COMPAT_ATTRIBUTE vec4 COLOR;
COMPAT_ATTRIBUTE vec4 TexCoord;
COMPAT_VARYING vec4 COL0;
COMPAT_VARYING vec4 TEX0;
 
uniform mat4 MVPMatrix;
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    _r0008 = VertexCoord.x*MVPMatrix[0];
    _r0008 = _r0008 + VertexCoord.y*MVPMatrix[1];
    _r0008 = _r0008 + VertexCoord.z*MVPMatrix[2];
    _r0008 = _r0008 + VertexCoord.w*MVPMatrix[3];
    _ret_0._position1 = _r0008;
    _ret_0._color1 = COLOR;
    _ret_0._texCoord = TexCoord.xy;
    gl_Position = _r0008;
    COL0 = COLOR;
    TEX0.xy = TexCoord.xy;
    return;
    COL0 = _ret_0._color1;
    TEX0.xy = _ret_0._texCoord;
} 
#elif defined(FRAGMENT)

#if __VERSION__ >= 130
#define COMPAT_VARYING in
#define COMPAT_TEXTURE texture
out vec4 FragColor;
#else
#define COMPAT_VARYING varying
#define FragColor gl_FragColor
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec2 _texCoord;
COMPAT_VARYING     vec4 _color;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct out_vertex {
    vec4 _color;
    vec2 _texCoord;
};
vec4 _ret_0;
vec4 _TMP48;
vec4 _TMP47;
vec4 _TMP46;
vec4 _TMP45;
float _TMP53;
float _TMP52;
float _TMP51;
float _TMP50;
float _TMP39;
float _TMP37;
float _TMP35;
float _TMP33;
float _TMP31;
float _TMP29;
float _TMP27;
float _TMP25;
float _TMP23;
float _TMP21;
float _TMP19;
float _TMP17;
float _TMP15;
float _TMP13;
float _TMP11;
float _TMP9;
vec4 _TMP38;
vec4 _TMP36;
vec4 _TMP34;
vec4 _TMP32;
vec4 _TMP30;
vec4 _TMP28;
vec4 _TMP26;
vec4 _TMP24;
vec4 _TMP22;
vec4 _TMP20;
vec4 _TMP18;
vec4 _TMP16;
vec4 _TMP14;
vec4 _TMP12;
vec4 _TMP10;
vec4 _TMP8;
float _TMP7;
float _TMP5;
float _TMP3;
float _TMP1;
vec4 _TMP6;
vec4 _TMP4;
vec4 _TMP2;
vec4 _TMP0;
uniform sampler2D Texture;
input_dummy _IN1;
vec2 _c0086;
vec2 _c0090;
vec2 _c0094;
vec2 _c0098;
vec2 _c0102;
vec2 _c0106;
vec2 _c0110;
vec2 _c0114;
vec2 _c0118;
vec2 _c0122;
vec2 _c0126;
vec2 _c0130;
vec2 _c0134;
vec2 _c0138;
vec2 _c0142;
vec2 _c0146;
vec2 _c0150;
vec2 _c0154;
vec2 _c0158;
vec2 _c0162;
vec2 _C0168[2];
vec2 _C0170[2];
vec2 _r0172;
float _TMP181;
float _x0182;
vec2 _c0188;
vec2 _c0190;
vec2 _c0192;
vec2 _c0194;
vec3 _C0196[1];
COMPAT_VARYING vec4 TEX0;
 
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    vec2 _tex;
    vec2 _R[2];
    vec2 _r;
    vec4 _y1;
    vec2 _a;
    vec3 _TMP59[2];
    vec2 _TMP63[2];
    vec2 _TMP64[2];
    vec2 _TMP65[4];
    _tex = TEX0.xy - vec2( 5.00000000E-01, 5.00000000E-01)/TextureSize;
    _c0086 = _tex + -vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP0 = COMPAT_TEXTURE(Texture, _c0086);
    _TMP1 = dot(_TMP0.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0090 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP2 = COMPAT_TEXTURE(Texture, _c0090);
    _TMP3 = dot(_TMP2.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0094 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 1.00000000E+00);
    _TMP4 = COMPAT_TEXTURE(Texture, _c0094);
    _TMP5 = dot(_TMP4.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0098 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -1.00000000E+00);
    _TMP6 = COMPAT_TEXTURE(Texture, _c0098);
    _TMP7 = dot(_TMP6.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _y1 = vec4(_TMP1, _TMP3, _TMP5, _TMP7);
    _c0102 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, -3.00000000E+00);
    _TMP8 = COMPAT_TEXTURE(Texture, _c0102);
    _TMP9 = dot(_TMP8.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0106 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP10 = COMPAT_TEXTURE(Texture, _c0106);
    _TMP11 = dot(_TMP10.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0110 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, 1.00000000E+00);
    _TMP12 = COMPAT_TEXTURE(Texture, _c0110);
    _TMP13 = dot(_TMP12.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0114 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -3.00000000E+00);
    _TMP14 = COMPAT_TEXTURE(Texture, _c0114);
    _TMP15 = dot(_TMP14.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0118 = _tex + -vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP16 = COMPAT_TEXTURE(Texture, _c0118);
    _TMP17 = dot(_TMP16.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0122 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, 3.00000000E+00);
    _TMP18 = COMPAT_TEXTURE(Texture, _c0122);
    _TMP19 = dot(_TMP18.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0126 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 3.00000000E+00);
    _TMP20 = COMPAT_TEXTURE(Texture, _c0126);
    _TMP21 = dot(_TMP20.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0130 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, -1.00000000E+00);
    _TMP22 = COMPAT_TEXTURE(Texture, _c0130);
    _TMP23 = dot(_TMP22.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0134 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, -1.00000000E+00);
    _TMP24 = COMPAT_TEXTURE(Texture, _c0134);
    _TMP25 = dot(_TMP24.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0138 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, 3.00000000E+00);
    _TMP26 = COMPAT_TEXTURE(Texture, _c0138);
    _TMP27 = dot(_TMP26.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0142 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, 3.00000000E+00);
    _TMP28 = COMPAT_TEXTURE(Texture, _c0142);
    _TMP29 = dot(_TMP28.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0146 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -1.00000000E+00);
    _TMP30 = COMPAT_TEXTURE(Texture, _c0146);
    _TMP31 = dot(_TMP30.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0150 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, -3.00000000E+00);
    _TMP32 = COMPAT_TEXTURE(Texture, _c0150);
    _TMP33 = dot(_TMP32.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0154 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, 1.00000000E+00);
    _TMP34 = COMPAT_TEXTURE(Texture, _c0154);
    _TMP35 = dot(_TMP34.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0158 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 1.00000000E+00);
    _TMP36 = COMPAT_TEXTURE(Texture, _c0158);
    _TMP37 = dot(_TMP36.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0162 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, -3.00000000E+00);
    _TMP38 = COMPAT_TEXTURE(Texture, _c0162);
    _TMP39 = dot(_TMP38.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _TMP65[0] = vec2(_TMP9 + _TMP11, _TMP13 + _TMP15);
    _TMP65[1] = vec2(_TMP17 + _TMP19, _TMP21 + _TMP23);
    _TMP65[2] = vec2(_TMP25 + _TMP27, _TMP29 + _TMP31);
    _TMP65[3] = vec2(_TMP33 + _TMP35, _TMP37 + _TMP39);
    _C0168[0] = _TMP65[0].x*_TMP65[0] + _TMP65[1].x*_TMP65[1] + _TMP65[2].x*_TMP65[2] + _TMP65[3].x*_TMP65[3];
    _C0170[1] = _TMP65[0].y*_TMP65[0] + _TMP65[1].y*_TMP65[1] + _TMP65[2].y*_TMP65[2] + _TMP65[3].y*_TMP65[3];
    _TMP64[0] = _C0168[0];
    _R[1] = _C0170[1];
    _r0172 = _y1.x*_TMP65[0];
    _r0172 = _r0172 + _y1.y*_TMP65[1];
    _r0172 = _r0172 + _y1.z*_TMP65[2];
    _r0172 = _r0172 + _y1.w*_TMP65[3];
    _r = _r0172;
    _c0086 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, -1.00000000E+00);
    _TMP0 = COMPAT_TEXTURE(Texture, _c0086);
    _TMP1 = dot(_TMP0.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0090 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, 1.00000000E+00);
    _TMP2 = COMPAT_TEXTURE(Texture, _c0090);
    _TMP3 = dot(_TMP2.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0094 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 3.00000000E+00);
    _TMP4 = COMPAT_TEXTURE(Texture, _c0094);
    _TMP5 = dot(_TMP4.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0098 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -3.00000000E+00);
    _TMP6 = COMPAT_TEXTURE(Texture, _c0098);
    _TMP7 = dot(_TMP6.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _y1 = vec4(_TMP1, _TMP3, _TMP5, _TMP7);
    _c0102 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -5.00000000E+00, -3.00000000E+00);
    _TMP8 = COMPAT_TEXTURE(Texture, _c0102);
    _TMP9 = dot(_TMP8.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0106 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 1.00000000E+00);
    _TMP10 = COMPAT_TEXTURE(Texture, _c0106);
    _TMP11 = dot(_TMP10.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0110 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -5.00000000E+00, 1.00000000E+00);
    _TMP12 = COMPAT_TEXTURE(Texture, _c0110);
    _TMP13 = dot(_TMP12.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0114 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, -3.00000000E+00);
    _TMP14 = COMPAT_TEXTURE(Texture, _c0114);
    _TMP15 = dot(_TMP14.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0118 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -1.00000000E+00);
    _TMP16 = COMPAT_TEXTURE(Texture, _c0118);
    _TMP17 = dot(_TMP16.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0122 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 5.00000000E+00, 3.00000000E+00);
    _TMP18 = COMPAT_TEXTURE(Texture, _c0122);
    _TMP19 = dot(_TMP18.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0126 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, 3.00000000E+00);
    _TMP20 = COMPAT_TEXTURE(Texture, _c0126);
    _TMP21 = dot(_TMP20.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0130 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 5.00000000E+00, -1.00000000E+00);
    _TMP22 = COMPAT_TEXTURE(Texture, _c0130);
    _TMP23 = dot(_TMP22.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0134 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, 1.00000000E+00);
    _TMP24 = COMPAT_TEXTURE(Texture, _c0134);
    _TMP25 = dot(_TMP24.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0138 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, 5.00000000E+00);
    _TMP26 = COMPAT_TEXTURE(Texture, _c0138);
    _TMP27 = dot(_TMP26.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0142 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, 5.00000000E+00);
    _TMP28 = COMPAT_TEXTURE(Texture, _c0142);
    _TMP29 = dot(_TMP28.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0146 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP30 = COMPAT_TEXTURE(Texture, _c0146);
    _TMP31 = dot(_TMP30.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0150 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, -5.00000000E+00);
    _TMP32 = COMPAT_TEXTURE(Texture, _c0150);
    _TMP33 = dot(_TMP32.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0154 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, -1.00000000E+00);
    _TMP34 = COMPAT_TEXTURE(Texture, _c0154);
    _TMP35 = dot(_TMP34.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0158 = _tex + -vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP36 = COMPAT_TEXTURE(Texture, _c0158);
    _TMP37 = dot(_TMP36.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0162 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, -5.00000000E+00);
    _TMP38 = COMPAT_TEXTURE(Texture, _c0162);
    _TMP39 = dot(_TMP38.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _TMP65[0] = vec2(_TMP9 + _TMP11, _TMP13 + _TMP15);
    _TMP65[1] = vec2(_TMP17 + _TMP19, _TMP21 + _TMP23);
    _TMP65[2] = vec2(_TMP25 + _TMP27, _TMP29 + _TMP31);
    _TMP65[3] = vec2(_TMP33 + _TMP35, _TMP37 + _TMP39);
    _C0168[0] = _TMP65[0].x*_TMP65[0] + _TMP65[1].x*_TMP65[1] + _TMP65[2].x*_TMP65[2] + _TMP65[3].x*_TMP65[3];
    _C0170[1] = _TMP65[0].y*_TMP65[0] + _TMP65[1].y*_TMP65[1] + _TMP65[2].y*_TMP65[2] + _TMP65[3].y*_TMP65[3];
    _TMP64[0] = _TMP64[0] + _C0168[0];
    _TMP64[1] = _R[1] + _C0170[1];
    _r0172 = _y1.x*_TMP65[0];
    _r0172 = _r0172 + _y1.y*_TMP65[1];
    _r0172 = _r0172 + _y1.z*_TMP65[2];
    _r0172 = _r0172 + _y1.w*_TMP65[3];
    _r = _r + _r0172;
    _c0086 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, 1.00000000E+00);
    _TMP0 = COMPAT_TEXTURE(Texture, _c0086);
    _TMP1 = dot(_TMP0.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0090 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, -1.00000000E+00);
    _TMP2 = COMPAT_TEXTURE(Texture, _c0090);
    _TMP3 = dot(_TMP2.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0094 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, 3.00000000E+00);
    _TMP4 = COMPAT_TEXTURE(Texture, _c0094);
    _TMP5 = dot(_TMP4.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0098 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, -3.00000000E+00);
    _TMP6 = COMPAT_TEXTURE(Texture, _c0098);
    _TMP7 = dot(_TMP6.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _y1 = vec4(_TMP1, _TMP3, _TMP5, _TMP7);
    _c0102 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -5.00000000E+00, -1.00000000E+00);
    _TMP8 = COMPAT_TEXTURE(Texture, _c0102);
    _TMP9 = dot(_TMP8.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0106 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 3.00000000E+00);
    _TMP10 = COMPAT_TEXTURE(Texture, _c0106);
    _TMP11 = dot(_TMP10.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0110 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -5.00000000E+00, 3.00000000E+00);
    _TMP12 = COMPAT_TEXTURE(Texture, _c0110);
    _TMP13 = dot(_TMP12.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0114 = _tex + -vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP14 = COMPAT_TEXTURE(Texture, _c0114);
    _TMP15 = dot(_TMP14.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0118 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -3.00000000E+00);
    _TMP16 = COMPAT_TEXTURE(Texture, _c0118);
    _TMP17 = dot(_TMP16.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0122 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 5.00000000E+00, 1.00000000E+00);
    _TMP18 = COMPAT_TEXTURE(Texture, _c0122);
    _TMP19 = dot(_TMP18.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0126 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP20 = COMPAT_TEXTURE(Texture, _c0126);
    _TMP21 = dot(_TMP20.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0130 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 5.00000000E+00, -3.00000000E+00);
    _TMP22 = COMPAT_TEXTURE(Texture, _c0130);
    _TMP23 = dot(_TMP22.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0134 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 1.00000000E+00);
    _TMP24 = COMPAT_TEXTURE(Texture, _c0134);
    _TMP25 = dot(_TMP24.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0138 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, 5.00000000E+00);
    _TMP26 = COMPAT_TEXTURE(Texture, _c0138);
    _TMP27 = dot(_TMP26.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0142 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 5.00000000E+00);
    _TMP28 = COMPAT_TEXTURE(Texture, _c0142);
    _TMP29 = dot(_TMP28.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0146 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 3.00000000E+00, 1.00000000E+00);
    _TMP30 = COMPAT_TEXTURE(Texture, _c0146);
    _TMP31 = dot(_TMP30.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0150 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, -5.00000000E+00);
    _TMP32 = COMPAT_TEXTURE(Texture, _c0150);
    _TMP33 = dot(_TMP32.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0154 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -1.00000000E+00);
    _TMP34 = COMPAT_TEXTURE(Texture, _c0154);
    _TMP35 = dot(_TMP34.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0158 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -3.00000000E+00, -1.00000000E+00);
    _TMP36 = COMPAT_TEXTURE(Texture, _c0158);
    _TMP37 = dot(_TMP36.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _c0162 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -5.00000000E+00);
    _TMP38 = COMPAT_TEXTURE(Texture, _c0162);
    _TMP39 = dot(_TMP38.xyz, vec3( 2.98999995E-01, 5.87000012E-01, 1.14000000E-01));
    _TMP65[0] = vec2(_TMP9 + _TMP11, _TMP13 + _TMP15);
    _TMP65[1] = vec2(_TMP17 + _TMP19, _TMP21 + _TMP23);
    _TMP65[2] = vec2(_TMP25 + _TMP27, _TMP29 + _TMP31);
    _TMP65[3] = vec2(_TMP33 + _TMP35, _TMP37 + _TMP39);
    _C0168[0] = _TMP65[0].x*_TMP65[0] + _TMP65[1].x*_TMP65[1] + _TMP65[2].x*_TMP65[2] + _TMP65[3].x*_TMP65[3];
    _C0170[1] = _TMP65[0].y*_TMP65[0] + _TMP65[1].y*_TMP65[1] + _TMP65[2].y*_TMP65[2] + _TMP65[3].y*_TMP65[3];
    _TMP64[0] = _TMP64[0] + _C0168[0];
    _TMP64[1] = _TMP64[1] + _C0170[1];
    _r0172 = _y1.x*_TMP65[0];
    _r0172 = _r0172 + _y1.y*_TMP65[1];
    _r0172 = _r0172 + _y1.z*_TMP65[2];
    _r0172 = _r0172 + _y1.w*_TMP65[3];
    _r = _r + _r0172;
    _TMP63[0] = _TMP64[0]/2.40000000E+01;
    _TMP63[1] = _TMP64[1]/2.40000000E+01;
    _r = _r/2.40000000E+01;
    _TMP50 = _r.x*_TMP63[1].y - _r.y*_TMP63[1].x;
    _TMP51 = _TMP63[0].x*_r.y - _TMP63[0].y*_r.x;
    _TMP52 = _TMP63[0].x*_TMP63[1].y - _TMP63[0].y*_TMP63[1].x;
    _a = vec2(_TMP50, _TMP51)/_TMP52;
    _x0182 = _a.x - _a.y;
    _TMP53 = min(1.00000000E+00, _x0182);
    _TMP181 = max(-1.00000000E+00, _TMP53);
    _a = 2.50000000E-01 + vec2( 5.00000000E-01, -5.00000000E-01)*_TMP181;
    _c0188 = _tex + -vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP45 = COMPAT_TEXTURE(Texture, _c0188);
    _c0190 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y));
    _TMP46 = COMPAT_TEXTURE(Texture, _c0190);
    _c0192 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( -1.00000000E+00, 1.00000000E+00);
    _TMP47 = COMPAT_TEXTURE(Texture, _c0192);
    _c0194 = _tex + vec2(1.00000000E+00/(2.00000000E+00*TextureSize.x), 1.00000000E+00/(2.00000000E+00*TextureSize.y))*vec2( 1.00000000E+00, -1.00000000E+00);
    _TMP48 = COMPAT_TEXTURE(Texture, _c0194);
    _TMP59[0] = _TMP45.xyz + _TMP46.xyz;
    _TMP59[1] = _TMP47.xyz + _TMP48.xyz;
    _C0196[0] = _a.x*_TMP59[0] + _a.y*_TMP59[1];
    _ret_0 = vec4(_C0196[0].x, _C0196[0].y, _C0196[0].z, 1.00000000E+00);
    FragColor = _ret_0;
    return;
} 
#endif
